# Generated by Django 5.2 on 2025-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Oddiy foydalanuvchi'), ('MASTER', 'Usta'), ('ADMIN', 'Admin')], default='USER', max_length=6),
        ),
    ]
