# Generated by Django 5.2 on 2025-04-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6),
        ),
    ]
